# Site settings
title: help.ona.io
email: support@ona.io
description: > # this means to ignore newlines until "baseurl:"
  This is the Ona help page.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://onalabs.org/help.ona.io" # the base hostname & protocol for your site
twitter_username: onadata
github_username:  help.ona.io

# Build settings
markdown: kramdown
highlighter: rouge
