# Site settings
title: "Help : Ona"
email: support@ona.io
description: > # this means to ignore newlines until "baseurl:"
  This is the Ona help page.
baseurl: "/"
url: "" #http://help.ona.io
twitter_username: onadata
github_username:  help.ona.io

# Build settings
markdown: kramdown
encoding: UTF-8
permalink: pretty
